### ISSUE TITLE
Root Finding Module

### ISSUE THREAD

**Issue by devanp92** [rreusser/spacetime.js#1]
Hey, I am coming here from numbers.js. You mention that you want to write an algo for finding complex roots. What about fixed point methods? Such as Bisection, Newton's, Secant, or even the basic quadratic equation? In the same light, I think this would fall under the 'linear algebra' module. What other modules are you planning to implement? For example, probability/statistics, etc.

**Comment by rreusser** [comment]
Thanks for the feedback! My motivation at the moment is guided wave calculations which result in complex transcendental equations (see: http://en.m.wikipedia.org/wiki/Lamb_waves ), so it requires a moderately robust solver.

The downside of the methods you mentioned is that they're sensitive to the initial guess and tend to miss roots that are too close. The really cool thing about integral methods is that as soon as you encircle the roots, you know exactly how many roots you need to find (well, roots - poles), and more than that, you can calculate N roots directly from N path integrals without searching at all!

I tried it before and have a python script lying around, but I wanted to dust this off and make it presentable online since there's a surprising amount of structure to the solution.

Or rather, I'm motivated to develop the tools with which it'd even be possible to present this sort of thing online.

**Comment by rreusser** [comment]
Sorry, so to answer your second question, the first goal is to put together a foundation that makes it clear how to start collecting assembling algorithms like this. The Python version is reasonably clean. I could do this in JS, but the foundation just isn't there to have much to show for it except lots of obfuscated workarounds for math libraries that aren't quite there yet. So yes, statistics and other things are definitely on the list, but I need a place to start and I figure a real application that requires a certain number of robust and organized pieces is a good starting point.

I've been looking at ndarray and math.js and I think things are close, but just not quite there yet. I'm hoping to find out how to make ndarray a central piece of a library that starts to feel kinda like numpy/scipy. That's a big undertaking though, so right now I'm trying to figure out what that foundation could look like.

I'd love to hear thoughts/criticisms/ideas/feedback!
